mavlink/MAVSDK-Python

other/tools/run_protoc.sh
This fixes #29. The problem was that sed on BSD is a bit different, see https://stackoverflow.com/questions/4247068/.
Needs cross-testing on Linux.
=> Fix macOS install

dronecode_sdk/__init__.py, examples/firmware_version.py, examples/mission.py, examples/takeoff_and_land.py, examples/telemetry_takeoff_and_land.py, other/templates/call.j2, other/templates/enum.j2, other/templates/file.j2, other/templates/request.j2, other/templates/stream.j2, other/templates/struct.j2
* Enable Calibration and Info plugins
* Add example for Info plugin (examples/firmware_version.py)
* Add support for return values (e.g. to actually get the version from the info plugin, instead of only querying it and never receiving it)
* Improve API by hiding gRPC (we now generate our own types, as in Swift)
=> Add support for return values

other/templates/call.j2, other/templates/request.j2, other/templates/stream.j2
* Close the stream from the client side when `SUCCESS` is sent (in the future, this should be done from the server side).
* Handle `IN_PROGRESS` and `INSTRUCTION` (in the future, those should disappear and only `SUCCESS` and `NEXT` will be success codes).
Tested with calibration and mission examples.
=> Handle SUCCESS, IN_PROGRESS and INSTRUCTION in streams

other/templates/stream.j2
Streams of empty responses were not generated correctly.
=> Fix template and update proto submodule

other/templates/struct.j2, other/tools/run_protoc.sh
* Fix generation for nested structs.
* Use `file_ext` option when running protoc, following latest changes in dcsdkgen
@zulufoxtrot: FYI
Resolves #47.
=> fix: use parent_type from type_info when translating struct

MANIFEST.in, dronecode_sdk/__init__.py, dronecode_sdk/bin/README.md, requirements.txt, setup.py
I modified the `setup.py` script so that it takes `dronecode_sdk/bin/backend_bin` as a resource. Then I added a `start_mavlink()` function that runs this binary in the background (and kills it when the main process dies, unless the main process is killed with e.g. `SIGKILL`).
The server can be run with something like:
```python
from dronecode_sdk import start_mavlink
start_mavlink()
```
I make the difference between python 3.7+ and python <= 3.7 by using respectively `importlib.resources` and `importlib_resources`.
@xvzf: I don't know how much of a hack this is, so I'd love to get your insights!
This is related to #20.
=> Support embedding of the grpc server binary (backend_bin)

dronecode_sdk/__init__.py
We should not do the call `backend_bin ""` because it complains about
invalid connection URL.
=> dronecode_sdk: fix start_mavlink() without arg

dronecode_sdk/__init__.py
There are a number of commits between the one for adding `offboard.proto` and the current commit hash (`a54b353d73`), need someone to verify it is OK to include them.
=> Update proto submodule with offboard proto def and core plugin list.

examples/offboard.py
I also added a little disclaimer about a couple of items, something I noticed when trying to use the `takeoff_and_land.py` example, pointed out by @julianoes. I'm not sure if the comments are worded correctly or need more context. I believe it's because LOITER and HOLD modes require some sort of home position for the RTL fail-safe, which is not available in non-gps set-ups?
=> Add offboard example

other/tools/run_protoc.sh
@unipheas: this should fix your build issue, but you may have to reinstall the plugin.
I tested in a venv with:
```sh
git clone https://github.com/dronecode/dronecodesdk-python
cd dronecodesdk-python
python -m venv venv
source ./venv/bin/activate
cd proto/pb_plugins
pip install -r requirements.txt
pip install -e .
cd ../..
pip install -r requirements.txt -r requirements-dev.txt
sh other/tools/run_protoc.h
which protoc-gen-dcsdk
```
=> dcsdkgen got renamed to protoc-gen-dcsdk

other/tools/run_protoc.sh
That should bring more consistent behavior between sh and bash on different platforms.
Resolves #69.
@unipheas: FYI
=> run_protoc.sh: use printf instead of echo 

setup.py
- I realized it has to be "Production" OR "Alpha" :laughing:.
- We don't support all of Python 3, so my hope is that setting Python 3.6 means that it works for Python 3.6+. @xvzf do you know about that?
=> dronecode_sdk: set development status and programming language

examples/calibration.py, examples/camera.py, examples/firmware_version.py, examples/mission.py, examples/offboard.py, examples/takeoff_and_land.py, examples/telemetry.py, examples/telemetry_flight_mode.py, examples/telemetry_is_armed_is_in_air.py, examples/telemetry_takeoff_and_land.py
From now on, we assume that users install our wheel package (`pip3 install mavsdk`) that contains `mavsdk_server` as a binary. The examples should therefore reflect that, by starting `mavsdk_server` at the beginning of the scripts:
```python
from mavsdk import start_mavlink
start_mavlink()
```
=> update examples for wheel

setup.py
Tested to work on my computer, and released to pypi.
@julianoes: can you try to `pip3 install mavsdk` on a mac and check that you get version `0.2.0`?
=> add macos to setup.py

other/templates/struct.j2
This is fix for [this PR](https://github.com/mavlink/MAVSDK-Python/pull/76).
I checked this fix on offboard.setActuatorControl() request. For this request all works ok but at this time I can not say that it will work for everything else.
I apologize for wrong implementation.
=> Fix for primitive types array rpc-gen template

mavsdk/generated/core.py, mavsdk/generated/mission.py, other/templates/request.j2
The templates were incorrect regarding returning a `repeated` type in a request (typically `download_mission()`). This PR addresses it.
@petergerten: would you mind reviewing this (possibly testing it)?
Resolves #138.
=> Fix mission download

LICENSE.txt
MAVSDK-Python is based on MAVSDK which is licensed under the BSD-3-Clause license already. Therefore, it makes sense to apply the same here.
Fixes #177.
=> Add BSD-3-Clause License

.travis.yml, mavsdk/system.py, setup.py
Running `MAVSDK_BUILD_PURE=ON python setup.py bdist_wheel` now creates a pure wheel that does not embed `mavsdk_server`. Travis publishes it to PyPi.
I had found a nicer solution not involving an env variable (it was `python setup.py build --pure`), but it did not work with `python setup.py bdist_wheel` :slightly_frowning_face:.
=> Publish pure wheel

examples/calibration.py
I decided to extend the example. Although, something weird seems to happen with the progress status text parsing during the accel calibration:
```sh
$ python3 calibration.py 
Waiting for mavsdk_server to be ready...
Connected to mavsdk_server!
-- Starting gyroscope calibration
ProgressData: [has_progress: True, progress: 0.0, has_status_text: False, status_text: ]
ProgressData: [has_progress: True, progress: 0.03999999910593033, has_status_text: False, status_text: ]
ProgressData: [has_progress: True, progress: 0.09000000357627869, has_status_text: False, status_text: ]
ProgressData: [has_progress: True, progress: 0.14000000059604645, has_status_text: False, status_text: ]
ProgressData: [has_progress: True, progress: 0.1899999976158142, has_status_text: False, status_text: ]
ProgressData: …
```
=> examples: extend calibration.py with other calibration routines

mavsdk/generated/action.py, mavsdk/generated/calibration.py, mavsdk/generated/camera.py, mavsdk/generated/follow_me.py, mavsdk/generated/ftp.py, mavsdk/generated/geofence.py, mavsdk/generated/gimbal.py, mavsdk/generated/info.py, mavsdk/generated/log_files.py, mavsdk/generated/mission.py, mavsdk/generated/mission_raw.py, mavsdk/generated/mocap.py, mavsdk/generated/offboard.py, mavsdk/generated/param.py, mavsdk/generated/shell.py, mavsdk/generated/telemetry.py, mavsdk/generated/tune.py, other/templates/enum.j2, other/templates/struct.j2
`translate_to_rpc` called for an enum from the `translate_to_rpc` of a struct had no effect, and was hence resulting in conversions.
It was not reported before because we don't really often use enums as parameters.
=> Fix translate_to_rpc for enums

mavsdk/system.py
Instead of a whole lot of exception output the user is now presented with the text below:
```
pi@rpi3-test:~/src/MAVSDK-Python $ examples/mission.py 
This installation does not provide an embedded 'mavsdk_server' binary.
If you installed using pip, this means that 'mavsdk_server' is not distributed
for your platform yet (e.g. arm).
You will need to get and run the 'mavsdk_server' binary manually:
1. Download 'mavsdk_server' from: https://github.com/mavlink/mavsdk/releases
or build it from source.
2. Run it, e.g. on port 50051:
'./mavsdk_server -p 50051'
3. Set the 'mavsdk_server_address' and port when creating the System:
'drone = System(mavsdk_server_address='localhost', port=50051)'
```
Also, the added plugins are added so they can be used.
=> Improve instructions for unsupported architectures

mavsdk/generated/camera.py, mavsdk/generated/geofence.py, mavsdk/generated/mission.py, mavsdk/generated/offboard.py, mavsdk/generated/tune.py, other/templates/py/struct.j2
Fixes #201.
@petergerten: would you mind testing this? On my end I can now load your `test.plan`.
=> Handle repeated non-primitive types in translate_from_rpc

other/templates/py/file.j2
To prevent things like https://github.com/mavlink/MAVSDK-Python/pull/213 in the future.
=> templates: add note that file is auto-generated

mavsdk/action.py, mavsdk/calibration.py, mavsdk/camera.py, mavsdk/core.py, mavsdk/follow_me.py, mavsdk/ftp.py, mavsdk/geofence.py, mavsdk/gimbal.py, mavsdk/info.py, mavsdk/log_files.py, mavsdk/mission.py, mavsdk/mission_raw.py, mavsdk/mocap.py, mavsdk/offboard.py, mavsdk/param.py, mavsdk/shell.py, mavsdk/system.py, mavsdk/telemetry.py, mavsdk/tune.py
When trying to create a wrapper [(MAVFleetControl)](https://github.com/julianblanco/MAVFleetControl) for mavsdk-python to control multiple aircraft, ran into an issue that the port for mavsdk server was hardcoded. Made changes allowing the user to specify the port and ensured default was the hard coded port (to hopefully not break other peoples code)
=> Added functionality to allow for mavsdk server port to be specified

other/tools/run_protoc.sh, setup.py
* Update proto submodule to use `protoc-gen-mavsdk` instead of `protoc-gen-dcsdk`
* Update scripts accordingly
* Fix license in setup.py (was apache, should be bsd)
=> Use protoc-gen-mavsdk (renamed from protoc-gen-dcsdk)

examples/goto.py
This is required because the goto altitude is absolute.
=> examples: closer goto, and go up, not down

examples/manual_control.py
Added a basic example showcasing the use of the manual control plugin. 
I could not find a way to implement joystick support without importing another pip package, so I decided to show manual input using some hard coded test input vectors. I believe this gets the point across, but the controls are very spastic (though it is fun to watching using jMAVsim).
=> Added manual_control Example

requirements.txt
I had protobuf 3.11.3 which gave me this error when importing mavsdk:
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
It is ok after updating protobuf to 3.13.0.
=> fix protobuf version

.github/workflows/main.yml
Turns out `linux_aarch64` is not ok.
=> Twine fix for Win and aarch64

mavsdk/camera.py, mavsdk/geofence.py, mavsdk/mission.py, mavsdk/offboard.py, mavsdk/param.py, mavsdk/tune.py, other/templates/py/struct.j2
Maps are lazy-evaluated. We want lists in this case, so they need to be converted.
=> Convert (lazy) maps to lists

examples/gimbal.py
This PR adds a Python example for controlling gimbals using MAVSDK-Python's various methods, as well as reading gimbal/camera attitude from telemetry.
=> Add gimbal example

mavsdk/system.py
I forgot to add this commit to my previous merge request.
It allow to automatically close mavsdk_server when launch by a mavsdk-python instance that is deleted
=> add a System destructor to kill mavsdk_server when an instance is removed

requirements-dev.txt
Note: to be merged after 1.0.1 is actually deployed (see [here](https://github.com/mavlink/MAVSDK-Proto/pull/210))
=> Update protoc-gen-mavsdk requirement

examples/follow_me_example.py
Some versions of PX4 fail with this example because GPS checks are passed before a home position is set. The example code tries to arm without home position then, which is rejected.
Here is the nuttx shell output for the original code
```
INFO  [ecl/EKF] 2568000: EKF aligned, (baro hgt, IMU buf: 18, OBS buf: 14)
INFO  [ecl/EKF] 2568000: reset position to last known position
INFO  [ecl/EKF] 2568000: reset velocity to zero
INFO  [ecl/EKF] 9876000: GPS checks passed                                   <----- GPS check passing
INFO  [commander] Armed by external command                               <----- armed by mavsdk
WARN  [commander] Failsafe enabled: No manual control stick input
INFO  [commander] Failsafe mode activated
WARN  [commander] Takeoff denied! Please disarm and retry
INFO …
```
=> follow_me_example: also check home position

mavsdk/async_plugin_manager.py, mavsdk/system.py
The print statements in the `async_plugin_manager` module can create visual clutter when connecting to multiple systems. Users should be able to decide if those statements are printed by configuring logging on an application level.
By default, if logging is configured the mavsdk connection messages should be printed. Users can easily silence them by selecting the appropriate logger and setting the level to anything above DEBUG.
Example:
```python
logging.getLogger("mavsdk.async_plugin_manager").setLevel(logging.INFO)
```
=> Replace print statements with logging statements

examples/takeoff_and_land_keyboard_control.py
A simple pygame used keyboard controller. Using the "Up Arrow" key, you can arm and take off the drone while using "Down Arrow" to land it. A special "i" button was added to display the current information of the drone as following: battery, whether the drone is in air or not, GPS, and finally the position. These were taken from `examples/takeoff_and_land.py` and `examples/telemetry.py` modules.
Requirements:
`pygame`
Installation: 
```bash
$pip3 install pygame
```
Run:
```bash
$python3 takeoff_and_land_keyboard_control.py
```
=> Takeoff and Land using Keyboard [pygame]

examples/goto.py
- Move goto location closer, otherwise this is confusing.
- Fix PEP8 warnings.
- Stay connected to avoid failsafe triggering.
=> examples: improve goto example

other/tools/run_protoc.sh
I stumbled over an incompatibility with the macOS version of sed. I got this solved by doing this little hack using the homebrew gnu-sed package. There might be better solutions but I am neither a bash nor an regex expert but I think I'd better come with a solution than a problem. 😄
=> macOS support for run_protoc.sh

examples/telemetry_takeoff_and_land.py, other/templates/py/call.j2, other/templates/py/request.j2, other/templates/py/stream.j2
This uses the `==`/`!=` operators instead of `is`/`is not` when checking the return value of RPC calls. In Python, `is not` tests if the  two operands are the same object whereas `!=` test that they have the same value. `is not` just happens to work for small integers due to an implementation detail in CPython (e.g. see [StackOverflow][1]).
[1]: https://stackoverflow.com/a/133024/1976323
=> Use `!=` instead of `is not` for values.

mavsdk/system.py
This allows to set the sysid and compid of the MAVSDK server but not actually the system, so the API is slightly odd.
=> system: allow setting sysid/compid

examples/shell.py
To test (against a real board, SITL won't work):
1. Create a venv (or don't, but that's what I do):
```
mkdir /tmp/test_mavshell && cd /tmp/test_mavshell
python -m venv venv
source ./venv/bin/activate
```
2. Install mavsdk (if not in a venv, use `pip install --user mavsdk` instead):
```
pip install mavsdk
```
3. Run the example:
```
python shell.py
```
Note: This assumes that you receive MAVLink on udp port 14540. If not, change the `await drone.connect(system_address="udp://:14540")` to listen to whatever you have (maybe `serial:///dev/ttyACM0`, maybe `udp://:14550`, you name it)
=> Add mavshell example

mavsdk/source/index.rst
=> docs: another try to fix formatting

examples/camera.py, examples/failure_injection.py, examples/firmware_version.py, examples/follow_me_example.py, examples/geofence.py, examples/goto.py, examples/logfile_download.py, examples/manual_control.py, examples/mission.py, examples/mission_import.py, examples/offboard_attitude.py, examples/offboard_position_ned.py, examples/offboard_position_velocity_ned.py, examples/offboard_velocity_body.py, examples/offboard_velocity_ned.py, examples/shell.py, examples/takeoff_and_land.py, examples/takeoff_and_land_keyboard_control.py, examples/telemetry_flight_mode.py, examples/telemetry_takeoff_and_land.py, examples/tune.py
Context: https://github.com/mavlink/MAVSDK-Python/issues/369#issuecomment-1073729797
A year ago I extended the check prior to arming from 
```
if health.is_global_position_ok
```
to 
```
if health.is_global_position_ok and health.is_home_position_ok:
```
because otherwise the PX4 preflight checks might fail if the python scripts are too quickly attempting to arm the drone after it acquired GPS.
Unfortunately I added this patch to only a few examples and not all of them. This PR is making up for that, and it also unifies the connection check at the beginning of almost every script. I don't mind the exact phrasing of the messages and whether it's "drone discovered" or "drone connected", but I think it's good to have it similar in all example scripts.
=> Same connection and GPS checks in all examples

examples/telemetry_takeoff_and_land.py
To make the example for `telemetry_takeoff_and_land` more representative  I propose to increase `MIS_TAKEOFF_ALT` parameter and sleep after taking off. 
```
Waiting for drone to connect...
-- Connected to drone!
Altitude: 0
Flight mode: LAND
-- Global position state is good enough for flying.
-- Setting takeoff altitude
-- Arming
-- Taking off
Flight mode: TAKEOFF
Altitude: 1
Altitude: 2
Altitude: 3
Altitude: 4
Altitude: 5
Altitude: 6
Altitude: 7
Altitude: 8
-- Landing
Flight mode: LAND
Altitude: 7
Altitude: 6
Altitude: 5
Altitude: 4
Altitude: 3
Altitude: 2
Altitude: 1
Altitude: 0
Altitude: -1
```
**UPD:**
Action has been used to increase takeoff altitude.
=> Increase takeoff altitude and sleep

examples/takeoff_and_land.py
We get many questions about why arming or takeoff fails with denied. One way to help a user would be to print the status text.
=> takeoff_and_land: print statustext

setup.py
The requirements in `requirements-dev.txt` are not actually required to run `setup.py` so this can be removed.
=> setup.py: drop setup_requires

requirements.txt
google.protobuf.descriptor_pool don't have `enum_types_by_name` field in version 3.13.0
When importing mavsdk, I get: 
```
File "C:\Users\fclav\anaconda3\lib\site-packages\mavsdk\__init__.py", line 7, in <module>
from .system import System
File "C:\Users\fclav\anaconda3\lib\site-packages\mavsdk\system.py", line 8, in <module>
from . import action
File "C:\Users\fclav\anaconda3\lib\site-packages\mavsdk\action.py", line 5, in <module>
from . import action_pb2, action_pb2_grpc
File "C:\Users\fclav\anaconda3\lib\site-packages\mavsdk\action_pb2.py", line 16, in <module>
from . import mavsdk_options_pb2 as mavsdk__options__pb2
File "C:\Users\fclav\anaconda3\lib\site-packages\mavsdk\mavsdk_options_pb2.py", line 21, in <module>
_ASYNCTYPE = DESCRIPTOR.enum_types_by_name['AsyncType'] …
```
=> update protobuf version

mavsdk/system.py
The `component_information_server` property in `system.py` uses the wrong key when returning the value leading to a KeyError. This changes that key to the proper one.
=> Fixed ComponentInformationServer key error

README.md
It went over my head that `-e` does not copy files to the system's default location until I googled it. Should we add this extra bit of information to the README?
=> readme: clarify on editable installation

.github/workflows/main.yml
For some reason it started failing with `error: invalid command 'bdist_wheel'`.
=> Fix macos ci

examples/manual_control.py
Think this needs to be fixed in the example -> [manual_control.py](https://github.com/mavlink/MAVSDK-Python/blob/2345933c5f14eb5da37569eb881fb9e86b68c4f4/examples/manual_control.py#L91)
The order of inputs _roll, pitch, throttle, yaw_ in the example seems to be incorrect.
The correct order needs to be _pitch, roll, throttle, yaw_ ([reference](https://github.com/mavlink/MAVSDK-Python/blob/2345933c5f14eb5da37569eb881fb9e86b68c4f4/mavsdk/manual_control.py#L254)).
Resolves #579
=> fixing order of inputs in python example script

examples/rtk.py
This shows how RTCM corrections can be sent using the Rtk plugin.
This will only work starting with MAVSDK server version https://github.com/mavlink/MAVSDK/releases/tag/v1.4.16 and thus MAVSDK-Python v1.4.8.
=> examples: add RTK example

examples/rtk_base_ublox.py
This example has a few prerequisites:
1. pyserial is installed
2. the uBlox base is connected via USB (otherwise the correct serial device has to be used in the code, or should we make it a command line argument?)
3. the uBlox base is properly configured. This code works even if it receives UBX/NMEA messages, but the user itself is in charge to configure the RTCM messages to be sent out. 
4. this code can directly connect to the drone; which means it cannot fly like this if attached via USB to the RTK base: Do we make the assumption everyone knows how to route mavlink?
Regarding 3: We could add some code to configure the uBlox device automatically via pyubx2 for example.
Tested against PX4 simulation:
=> examples: add RTK example with uBlox base

README.md, mavsdk/source/index.rst, mavsdk/source/jetson-nano-install.rst
@AlexKlimaj this is for Ubuntu 18.04. It would be nice if you could help me with Ubuntu 20.04 instructions.
=> Badge fix and Jetson install

README.md, examples/gripper.py, examples/winch.py, mavsdk/system.py
- Proto: https://github.com/mavlink/MAVSDK-Proto/pull/308
- MAVSDK: https://github.com/mavlink/MAVSDK/pull/1958
- MAVSDK-Python: https://github.com/mavlink/MAVSDK-Python/pull/545  **(this PR)**
Adds the winch and gripper plugins also to MAVSDK-Python.
The example scripts are a bit tricky, since there is currently no simulation counterpart against which they can be used. They work in the sense that they send the corresponding commands, but MAVSDK will not receive an ACK if there is no winch or gripper component connected to MAVSDK. I don't know how we want to handle this for example scripts. 
After updating the proto submodule and regenerating the python part, I got quite a lot of changes across the board and I'm not sure what needs to be committed:
```
mavsdk/action.py                | …
```
=> Winch and Gripper plugins

examples/geofence.py
The process of setting the geofence in V1 was different than V2, so this change updated the geofence process according to the need of V2. Geofence class is changed.
=> Geofence mechanism is updated according to V2.1.0.

examples/mission_raw.py
- Updated [MAV_FRAME](https://mavlink.io/en/messages/common.html#MAV_FRAME) command from 6 (deprecated) to 3 (newly updated WGS84 + rel. system)
- Also added a few comments to make comprehension easier
- Refactored file
=> Updated raw mission example + removed deprecations

examples/follow_me_example.py
* Replace `direction = Config.FollowDirection.BEHIND` with `follow_angle_deg = 0` in `follow_me_example.py`
* Add new required args to follow_me `Config()`
- [2020-08-16] **MAVSDK-Python** - `follow_me_example.py` added ([commit](https://github.com/mavlink/MAVSDK-Python/commit/8f916f0cd22e03c284419bacf6510a3efc8999d5))
- [2022-06-30] **MAVSDK-Proto** - `FollowDirection` enum and arg removed (https://github.com/mavlink/MAVSDK-Proto/pull/287#issuecomment-1132930474)
- [2024-01-27] **MAVSDK-Python** - `Config.FollowDirection` enum removed ([commit](https://github.com/mavlink/MAVSDK-Python/commit/8f8e81fb89914a2e98a9c9657230a08024edbb6c#diff-56d8fb7ac5ee5dc89721d8b0b2ada70565e3d2f314c500a05e0d2644de7378efL31))
=> Update follow_me_example to use MAVSDK v2

examples/follow_me_example.py
Fix Follow Me example by explicitly setting a non-zero value for absolute_altitude_m in target_location
=> Fix Follow Me example

examples/highres_imu.py
I have created a python file that prints the IMU data from the FC
=> Example to print IMU data

examples/gimbal.py
The Gimbal API changed quite a bit in MAVSDK 3.0.0. This updates the example to work with the new API.
It added multi gimbal support, and almost all calls need a gimbal ID.
set_pitch_and_yaw is removed and I have replaced it with the new set_angles.
It has been test on real hardware, with a PX4 v1.15.2 orange cube and a Gremsy T3v3 and T7.
=> Updated to function with the changes of MAVSDK 3.0.0

examples/rtk_base_ublox.py
Due to MAVSDK V3 use RTCM base64 encoded string . 
This PR refactored "rtk_base_ublox.py" in the example code .
=> Update Ublox RTK example 

.github/workflows/main.yml
Four instances:
https://github.com/mavlink/MAVSDK-Python/blob/edb9213199722a954e7d82f9c2f98df20d19f361/.github/workflows/main.yml#L40
https://github.com/mavlink/MAVSDK-Python/blob/edb9213199722a954e7d82f9c2f98df20d19f361/.github/workflows/main.yml#L107
https://github.com/mavlink/MAVSDK-Python/blob/edb9213199722a954e7d82f9c2f98df20d19f361/.github/workflows/main.yml#L156
https://github.com/mavlink/MAVSDK-Python/blob/edb9213199722a954e7d82f9c2f98df20d19f361/.github/workflows/main.yml#L207
In the macOS or Windows `Create wheel` section, please see the warning:
```
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/setuptools/_distutils/cmd.py:90: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!! …
```
=> `setup.py bdist_wheel` is deprecated and will be disabled in Oct. 2025

examples/mavlink_direct_receive.py, examples/mavlink_direct_send.py
This is to demonstrate the new MavlinkDirect functionality.
=> examples: add two MavlinkDirect examples

examples/show_debug_output.py
This should now work properly thanks to this fix:
https://github.com/mavlink/MAVSDK/pull/2631
=> examples: add demo to show all mavsdk_server output
