tools/run_protoc.sh
=> run_protoc.sh should only consider directories in proto/

README.md
Worth doing this because it isn't always obvious to readers that they need to update submodules.
=> Update readme with cloning steps

other/tools/run_protoc.sh, setup.py
=> Fixes import issue for the generated files.

dronecore/__init__.py, examples/telemetry_viewer.py
Temporary fix until I manage to get a PR up for RxPy!
=> Added option to exit the program

other/docker/testing/Dockerfile, tox.ini
Since Python 3.7 was released a couple of weeks ago, it might be worth adding it to the test suite!
=> Add Python 3.7 to the test suite

other/tools/run_protoc.sh
The previous solution of using bash string substitution is limited to
bash >4.0, currently macos ships with bash 3.2, this implements a
solution based on python 3
=> build: fixes capitalization of a string in macos

other/tools/run_protoc.sh
@JonasVautherin FYI @julianoes Fixes your issue when `python2` is still the default
=> Enforce python3

examples/takeoff_and_land.py, examples/telemetry_flight_mode.py, examples/telemetry_is_armed_is_in_air.py, examples/telemetry_takeoff_and_land.py, other/templates/enum.j2, other/templates/stream.j2, other/templates/struct.j2
Fixed a few more bugs in the generation, which shows that it will be helpful to generate unit tests (but that will come).
=> Add telemetry examples

examples/telemetry_takeoff_and_land.py
@JonasVautherin I adapted the example to give an example on how to setup coroutines in larger scale applications!
=> Different approach to create the tasks for the eventloop

examples/telemetry_takeoff_and_land.py
@JonasVautherin FYI, I missed that `create_task` only works when the event loop is running
=> Fixes previously updated example

README.md
Let's have markdown docs everywhere for the Dronecode SDK.
=> README: move from .rst to .md

setup.py
Related to https://github.com/Dronecode/DronecodeSDK-Python/pull/33
=> Moving to md files broke setup.py

dronecode_sdk/__init__.py
This should allow to connect using any connection, not just the default UDP connection on port 14540.
This needs testing, I couldn't test it yet on my end.
=> dronecode_sdk: allow passing of connection URL

dronecode_sdk/__init__.py, examples/takeoff_and_land.py
Wait for the drone to be discovered in the `takeoff_and_land.py` example.
=> example: discover drone in takeoff example

README.md
@unipheas: I integrated some of your suggestions. Feel free to open a PR in this repo if you think something is unclear!
@xvzf: FYI, the backend now uses cmake only
=> readme: update with the new way of building the backend

README.md
@xvzf: FYI: we can now `pip install mavsdk` :tada:
=> Update README to include pip instructions

other/templates/struct.j2
Needed to https://github.com/mavlink/MAVSDK-Proto/pull/87
=> Add translates for primitive type arrays

README.md, mavsdk/bin/README.md
This should avoid some confusion.
=> READMEs: always use python3 and pip3

examples/calibration.py, examples/firmware_version.py, examples/mission.py, examples/offboard.py, examples/takeoff_and_land.py, examples/telemetry.py, examples/telemetry_flight_mode.py, examples/telemetry_is_armed_is_in_air.py, examples/telemetry_takeoff_and_land.py
First step before renaming as discussed in #86.
=> explicit connection_url when calling start_mavlink

mavsdk/generated/__init__.py, mavsdk/generated/telemetry.py, mavsdk/generated/telemetry_pb2.py, mavsdk/generated/telemetry_pb2_grpc.py
Due to https://github.com/mavlink/MAVSDK-Proto/pull/107
=> Add Odometry and LandedState to telemetry plugin

examples/calibration.py, examples/camera.py, examples/firmware_version.py, examples/mission.py, examples/offboard_attitude.py, examples/offboard_velocity_body.py, examples/offboard_velocity_ned.py, examples/takeoff_and_land.py, examples/telemetry_flight_mode.py, examples/telemetry_takeoff_and_land.py
I had a pass through the examples to make sure the PEP8 linter wasn't complaining and to check that they run against SITL.
=> Improve examples

.travis.yml
=> travis-ci: try to deploy to PyPi using twine

.travis.yml
It's sad that this is needed.
The problem seems to be that we can't upload the same file twice to PyPi just with another name.
=> travis-ci: add Windows 32 bit

setup.py
This suddenly seems to be necessary.
=> setup.py: add type of long_description

examples/offboard_position_ned.py
Action no longer changes to LOITER/HOLD first.
=> examples: remove comment which is no longer true

examples/camera.py, examples/mission.py, examples/telemetry_takeoff_and_land.py
See discussion here: https://bugs.python.org/issue38559
Before calling `aclose()` (which is called by `shutdown_asyncgens()`), Python 3.8 requires the tasks to be cancelled.
=> Fix tasks termination for Python 3.8

.travis.yml, README.md, mavsdk/source/conf.py
And also clarify release process in README.
=> Generate API docs in CI

other/tools/upload_docs.sh
This was wrong before and some pages were not uploaded correctly.
=> tools: upload everything properly

mavsdk/source/conf.py
=> sphinx: fix path to create docs

mavsdk/log_files.py, mavsdk/mission_raw.py, other/templates/py/stream.j2
Somehow I did not manage to update #213.
Thanks @Nicole426!
=> Fix misspelling in mission_raw.py 

examples/goto.py
Thanks to @iwishiwasaneagle for providing the example in #233.
=> Added goto example

examples/offboard_attitude.py
=> Examples: improve offboard attitude

mavsdk/source/plugins/index.rst, mavsdk/system.py
I think we forgot this. Did I miss it anywhere else?
=> mavsdk: add manual_control plugin

examples/follow_me_example.py, examples/goto.py
Added an example on how to use the FollowMe plugin and updated the goto.py example with some code that allows user to get the absolute terrain altitude and then use it to fly the drone. This helps in flying the drone irrespective of the location as we can just provide values relative to that altitude.
=> Examples: Added FollowMe example and updated goto.py

examples/geofence.py
Minor changes. The imports were not working correctly before, and I decided to create the boundary around the home point instead of a hard coded location
=> Updated the Geofence Example

.github/workflows/main.yml
We need this to run on version tag
=> workflows: run on any tag

.github/workflows/main.yml
=> Fix twine upload

.github/workflows/main.yml
=> workflows: fix twine again

mavsdk/camera.py, other/templates/py/stream.j2
Necessary for the camera settings.
=> Add repeated non-primitive support to streams

examples/camera_params.py, examples/follow_me_example.py, examples/manual_control.py
This is a small example where the user can list the available camera parameters and set them interactively.
=> Add camera params example

mavsdk/system.py
I have a lot of issues trying to connect to my autopilot. Sometimes, it fail because the autopilot boot is not complete or serial port is locked elsewhere. If my connection fail, I cannot retry because mavsdk server is blocked in the error.
On connection, I added a restart of the server if it is already running and was launch by this instance of mavsdk-python. It allows me retry to connect.
It also gives an access to stop a server internally launched.
I am not sure this is a good way to do this. Are you ok with that or do you have suggestions ?
=> add mavsdk_server restart if already running at connection

mavsdk/system.py
=> Added Failure Plugin

.github/workflows/main.yml, README.md, mavsdk/source/index.rst, other/templates/py/file.j2
Also see https://github.com/github/renaming.
=> Switch from master to main branch

README.md
Just realized this was missing.
=> README: add release step for proto check

requirements-docs.txt
I will have to do another release for this to upload.
=> requirements-docs: add s3cmd to upload docs

examples/gimbal.py
This adds a few more demo steps, as well as takes and releases control.
=> examples: improve gimbal example

examples/mission.py
Fixes https://github.com/mavlink/MAVSDK/issues/1496.
=> Fix misson example

README.md
=> Readme-spelling

examples/mission.py
New Mission item requires an additional argument camera_photo_distance_m
=> Update mission example after Mission item API changed

mavsdk/source/index.rst
This is a question that comes up again and again, so let's add some help around it.
=> docs: add note how to debug concection issues

mavsdk/source/index.rst
Maybe some day I'll understand restructured text.
=> docs: fix formatting

examples/failure_injection.py
Very basic python example for failure injection. Drone takes off, flies to a higher altitude and then receives a GPS failure injection, upon which it will failsafe and land.
Tested with px4_sitl / jmavsim
=> Failure injection example script

mavsdk/system.py
Enabling:
1. ServerUtility plugin
2. TelemetryServer plugin
=> Enable server plugins

examples/send_status_message.py
=> Add example for server_utility plugin

mavsdk/system.py, setup.py
Fixed the executables extention to start the mavlink server on windows
@JonasVautherin
=> Pr fix windows installation

examples/camera_params.py
=> Handle range params in camera_params example

examples/gimbal.py
=> examples: exit gimbal script

examples/telemetry_status_text.py
Works for me.
@JonasVautherin note this has the new way of running stuff with `asyncio` in Python 3.10.
=> example: add status_text example

examples/all_params.py
I asked ChatGPT but it couldn't do it, so I had to do the work myself.
References:
http://mavsdk-python-docs.s3-website.eu-central-1.amazonaws.com/plugins/param.html#mavsdk.param.Param.get_all_params
http://mavsdk-python-docs.s3-website.eu-central-1.amazonaws.com/plugins/param.html#mavsdk.param.AllParams
FYI @AlexKlimaj
=> examples: add example to fetch all params

requirements-dev.txt
This should fix the docs generation.
=> Require protoc-gen-mavsdk 1.1.1

examples/mission_raw.py
As an example how to set seq and current.
=> examples: add simple mission_raw example

mavsdk/source/index.rst, mavsdk/source/plugins/index.rst
Signed-off-by: Julian Oes <julian@oes.ch>
=> docs: try to fix depth of index

examples/upload_params.py
In honor of this PR: https://github.com/mavlink/MAVSDK-Python/pull/558
cc: @julianoes @afwilkin
=> Examples: Add files via upload

examples/px4_ev_automation.py, examples/px4_ev_automation_keyboard.py
In favor of [#609](https://github.com/mavlink/MAVSDK-Python/pull/609)
I preferred to Squash the commits!
FYI: @afwilkin @julianoes
=> Continuing #609

examples/follow_me_example.py
=> examples: fix follow-me main function name

examples/telemetry_is_armed_is_in_air.py
I am referencing a non-existent method. I will change it.
=> examples: Change the method of citation

examples/ftp_download_file.py, examples/ftp_list_dir.py
Thanks to @jhadevansh08 for the example.
=> Add example how to list directory

mavsdk/system.py
And fixup a copy paste mistake.
=> Add missing plugins

.github/workflows/main.yml
I don't think this should change anything.
=> CI: bump Ubuntu to 24.04
